### ISSUE TITLE
Undefined method from NoParensEmptyInstantiations lint

### ISSUE THREAD

**Issue by Juddling** [tightenco/tlint#14]
Using PHP 7.1.11

If you need any other info, let me know. This is a great package, will look to send you some PRs soon!

```
PHP Fatal error:  Uncaught Error: Call to undefined method PhpParser\Node\Expr\Variable::toString() in /Users/macbook/.composer/vendor/loganhenson/tlint/src/Linters/NoParensEmptyInstantiations.php:24
Stack trace:
#0 /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeVisitor/FindingVisitor.php(41): Tighten\Linters\NoParensEmptyInstantiations->Tighten\Linters\{closure}(Object(PhpParser\Node\Expr\New_))
#1 /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(115): PhpParser\NodeVisitor\FindingVisitor->enterNode(Object(PhpParser\Node\Expr\New_))
#2 /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(197): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Return_))
#3 /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(108): PhpParser\NodeTraverser->traverseArray(Array)
#4 /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(197): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node in /Users/macbook/.composer/vendor/loganhenson/tlint/src/Linters/NoParensEmptyInstantiations.php on line 24

Fatal error: Uncaught Error: Call to undefined method PhpParser\Node\Expr\Variable::toString() in /Users/macbook/.composer/vendor/loganhenson/tlint/src/Linters/NoParensEmptyInstantiations.php on line 24

Error: Call to undefined method PhpParser\Node\Expr\Variable::toString() in /Users/macbook/.composer/vendor/loganhenson/tlint/src/Linters/NoParensEmptyInstantiations.php on line 24

Call Stack:
    0.0003     357824   1. {main}() /Users/macbook/.composer/vendor/loganhenson/tlint/bin/tlint:0
    0.0315    1606216   2. Symfony\Component\Console\Application->run() /Users/macbook/.composer/vendor/loganhenson/tlint/bin/tlint:34
    0.0511    1855152   3. Symfony\Component\Console\Application->doRun() /Users/macbook/.composer/vendor/symfony/console/Application.php:148
    0.0515    1857944   4. Symfony\Component\Console\Application->doRunCommand() /Users/macbook/.composer/vendor/symfony/console/Application.php:240
    0.0515    1857944   5. Tighten\Commands\LintCommand->run() /Users/macbook/.composer/vendor/symfony/console/Application.php:938
    0.0517    1859352   6. Tighten\Commands\LintCommand->execute() /Users/macbook/.composer/vendor/symfony/console/Command/Command.php:252
   12.7301    9493792   7. Tighten\Commands\LintCommand->lintFile() /Users/macbook/.composer/vendor/loganhenson/tlint/src/Commands/LintCommand.php:203
   12.7699   10092120   8. Tighten\TLint->lint() /Users/macbook/.composer/vendor/loganhenson/tlint/src/Commands/LintCommand.php:89
   12.7699   10092816   9. Tighten\Linters\NoParensEmptyInstantiations->lint() /Users/macbook/.composer/vendor/loganhenson/tlint/src/TLint.php:27
   12.7730   10085784  10. PhpParser\NodeTraverser->traverse() /Users/macbook/.composer/vendor/loganhenson/tlint/src/Linters/NoParensEmptyInstantiations.php:30
   12.7730   10085784  11. PhpParser\NodeTraverser->traverseArray() /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:85
   12.7730   10086208  12. PhpParser\NodeTraverser->traverseNode() /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:197
   12.7730   10086304  13. PhpParser\NodeTraverser->traverseArray() /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:108
   12.7731   10087784  14. PhpParser\NodeTraverser->traverseNode() /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:197
   12.7732   10087984  15. PhpParser\NodeTraverser->traverseArray() /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:108
   12.7732   10088408  16. PhpParser\NodeTraverser->traverseNode() /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:197
   12.7732   10088792  17. PhpParser\NodeTraverser->traverseArray() /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:108
   12.7734   10090496  18. PhpParser\NodeTraverser->traverseNode() /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:197
   12.7734   10090520  19. PhpParser\NodeVisitor\FindingVisitor->enterNode() /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:115
   12.7734   10090520  20. Tighten\Linters\NoParensEmptyInstantiations->Tighten\Linters\{closure}() /Users/macbook/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeVisitor/FindingVisitor.php:41
```

**Comment by loganhenson** [comment]
Hey thank you for the issue!

I'm thinking this comes from an edge case I missed where instantiating a new class from a variable:

`$class = Thing::class; $object = new $class`

Let me know if this fixes your issue please 👍

**Comment by Juddling** [comment]
@loganhenson thanks for this! 

Will check for you but I can't pull the latest yet - can you please update packagist dev-master, which is currently on commit a02062ef71b8115e1448c3c7a1de17176cc9dd2d
